[package]
name = "oxvox"
version = "1.0.0"
edition = "2024"
authors = ["Hamish Morgan <ham430@gmail.com>"]
description = "Performant operations on array & pointcloud data, written in Rust"
readme = "README.md"
repository = "https://github.com/hacmorgan/oxvox"
license-file =  "LICENSE"
keywords = ["nearest", "neighbour", "pointcloud", "array", "ndarray", "python"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "oxvox"
crate-type = ["cdylib"]

[dependencies]
bincode = "1.3.3"
numpy = "0.29"
ndarray = {version = "0.17.2", features=["serde", "rayon"]}
pyo3 = { version = "0.29", features = ["abi3-py310"] }
rayon = "1.12"
serde = {version = "1.0.229", features = ["derive"]}
indicatif = {version = "0.18", features = ["rayon"]}
ahash = {version = "0.8.8", features = ["serde"]}
